# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrontendLouie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LouieBot(object):
    def setupUi(self, LouieBot):
        LouieBot.setObjectName("LouieBot")
        LouieBot.resize(1092, 649)
        self.centralwidget = QtWidgets.QWidget(LouieBot)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 5, 1091, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 611, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P2.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 90, 621, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P3.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 451, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P4.PNG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 50, 271, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P5.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(830, 370, 201, 121))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("/Users/hk452/Desktop/GIF/P6.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 150, 71, 31))
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 240, 291, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"border-color:none;\n"
"border-none;\n"
"border-radius:none;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(840, 320, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(950, 320, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(203, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(80, 90, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"border-color:none;\n"
"border-none;\n"
"border-radius:none;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(870, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: transparent;\n"
"border-color:none;\n"
"border-none;\n"
"border-radius:none;\n"
"font-size:20px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        LouieBot.setCentralWidget(self.centralwidget)

        self.retranslateUi(LouieBot)
        QtCore.QMetaObject.connectSlotsByName(LouieBot)

    def retranslateUi(self, LouieBot):
        _translate = QtCore.QCoreApplication.translate
        LouieBot.setWindowTitle(_translate("LouieBot", "MainWindow"))
        self.label_3.setStyleSheet(_translate("LouieBot", "background-color: transparent;\n"
"border-color:none;\n"
"border-none;\n"
"border-radius:none;\n"
""))
        self.label_7.setText(_translate("LouieBot", "TextLabel"))
        self.pushButton.setText(_translate("LouieBot", "RUN"))
        self.pushButton_3.setText(_translate("LouieBot", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LouieBot = QtWidgets.QMainWindow()
    ui = Ui_LouieBot()
    ui.setupUi(LouieBot)
    LouieBot.show()
    sys.exit(app.exec_())
